# Generated by Django 5.2.2 on 2026-09-21 08:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('operating', 'Operating expense'), ('utility', 'Utility (shared — apportioned)'), ('capital_works', 'Capital works / structural'), ('mortgage', 'Interest / mortgage'), ('other', 'Other')], default='operating', max_length=20)),
                ('default_apportionment', models.CharField(choices=[('none', 'No apportionment (100% deductible)'), ('area', 'By floor area of the let'), ('custom', 'Custom percentage')], default='none', max_length=10)),
                ('details', models.CharField(blank=True, help_text='Accountant-facing label / notes.', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('airbnb', 'Airbnb'), ('other', 'Other platform')], default='airbnb', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('external_id', models.CharField(blank=True, help_text='Airbnb listing id (optional).', max_length=100)),
                ('url', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['property__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_floor_area_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='Whole dwelling / property floor area (m²).', max_digits=9, null=True)),
                ('rental_floor_area_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='Floor area exclusively used for the short-stay let (m²).', max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('airbnb_csv', 'Airbnb transaction CSV'), ('airbnb_browser', 'Airbnb browser pull'), ('other', 'Other')], default='airbnb_csv', max_length=30)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_created', models.PositiveIntegerField(default=0)),
                ('rows_updated', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('rows_failed', models.PositiveIntegerField(default=0)),
                ('log', models.TextField(blank=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='ledger.listing')),
            ],
            options={
                'verbose_name_plural': 'import batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='ledger.property'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Gross amount including GST.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='GST included in ``amount`` (for GST-registered entities).', max_digits=12)),
                ('apportionment', models.CharField(choices=[('none', 'No apportionment (100% deductible)'), ('area', 'By floor area of the let'), ('custom', 'Custom percentage')], default='none', max_length=10)),
                ('apportionment_pct', models.DecimalField(blank=True, decimal_places=4, help_text='Override fraction (0..1). Leave blank to use the floor-area share.', max_digits=6, null=True)),
                ('deductible_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('paid', models.BooleanField(default=True)),
                ('payment_method', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('airbnb_csv', 'Airbnb CSV import'), ('other', 'Other import')], default='manual', max_length=30)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='ledger.category')),
                ('listing', models.ForeignKey(blank=True, help_text='Set only if the cost relates to the listing specifically.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='ledger.listing')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='ledger.property')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('plant_equipment', 'Plant & equipment'), ('capital_works', 'Capital works (building)'), ('other', 'Other')], default='plant_equipment', max_length=20)),
                ('purchase_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost (incl. any installation / GST as applicable).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('effective_life_years', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('method', models.CharField(choices=[('prime_cost', 'Prime cost (straight line)'), ('diminishing_value', 'Diminishing value')], default='diminishing_value', max_length=20)),
                ('business_use_pct', models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='Business/rental use fraction (0..1).', max_digits=6)),
                ('low_value_pool', models.BooleanField(default=False, help_text='Pooled (e.g. cost below the ATO low-value threshold).')),
                ('disposed_date', models.DateField(blank=True, null=True)),
                ('disposal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='ledger.property')),
            ],
            options={
                'ordering': ['-purchase_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='receipts/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='ledger.asset')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='ledger.expense')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='ledger.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_year', models.CharField(help_text='e.g. FY2025-26', max_length=12)),
                ('method', models.CharField(choices=[('prime_cost', 'Prime cost (straight line)'), ('diminishing_value', 'Diminishing value')], max_length=20)),
                ('opening_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('closing_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('days_held', models.PositiveIntegerField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_entries', to='ledger.asset')),
            ],
            options={
                'verbose_name_plural': 'depreciation entries',
                'ordering': ['asset', 'financial_year'],
                'constraints': [models.UniqueConstraint(fields=('asset', 'financial_year'), name='uniq_depreciation_per_asset_fy')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmation_code', models.CharField(help_text='Airbnb confirmation code — used to de-duplicate imports.', max_length=64)),
                ('guest_name', models.CharField(blank=True, max_length=200)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('nights', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='AUD', max_length=3)),
                ('accommodation_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cleaning_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('airbnb_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Airbnb service fee (positive number = amount withheld).', max_digits=12)),
                ('taxes_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payout_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='completed', max_length=20)),
                ('source', models.CharField(default='airbnb_csv', max_length=30)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='ledger.listing')),
            ],
            options={
                'ordering': ['-check_in', '-payout_date'],
                'constraints': [models.UniqueConstraint(fields=('listing', 'confirmation_code'), name='uniq_reservation_per_listing')],
            },
        ),
    ]
