# Generated by Django 5.2.2 on 2026-09-21 10:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='importbatch',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='property',
            name='default_depreciation_method',
            field=models.CharField(choices=[('diminishing_value', 'Diminishing value'), ('prime_cost', 'Prime cost (straight line)')], default='diminishing_value', help_text='Default decline-in-value method for new assets. See the ATO for the implications: https://www.ato.gov.au/individuals-and-families/investments-and-assets/property-and-land/residential-rental-properties', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='gst_registered',
            field=models.BooleanField(default=False, help_text='Is the host registered for GST? Affects GST treatment on income/expenses.'),
        ),
        migrations.AddField(
            model_name='property',
            name='let_percentage',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Fraction of the dwelling let for income (0..1). Leave blank to derive it from the floor areas above. E.g. 0.3000 = 30%.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='method',
            field=models.CharField(choices=[('diminishing_value', 'Diminishing value'), ('prime_cost', 'Prime cost (straight line)')], default='diminishing_value', max_length=20),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='source',
            field=models.CharField(choices=[('airbnb_csv', 'Airbnb transaction CSV'), ('airbnb_pdf', 'Airbnb earnings-report PDF'), ('airbnb_browser', 'Airbnb browser pull'), ('other', 'Other')], default='airbnb_csv', max_length=30),
        ),
        migrations.CreateModel(
            name='MonthlyEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField()),
                ('currency', models.CharField(default='AUD', max_length=3)),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('adjustments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('service_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Airbnb service fees (negative = withheld).', max_digits=12)),
                ('tax_withheld', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net total (AUD).', max_digits=12)),
                ('source', models.CharField(default='airbnb_pdf', max_length=30)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_earnings', to='ledger.listing')),
            ],
            options={
                'verbose_name_plural': 'monthly earnings',
                'ordering': ['-month'],
                'constraints': [models.UniqueConstraint(fields=('listing', 'month'), name='uniq_monthly_earnings')],
            },
        ),
        migrations.CreateModel(
            name='PropertyOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share_pct', models.DecimalField(decimal_places=4, help_text='Ownership fraction (0..1). E.g. 0.5000 = 50%.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='ledger.owner')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='ledger.property')),
            ],
            options={
                'verbose_name_plural': 'property ownerships',
                'ordering': ['property__name', 'owner__name'],
                'constraints': [models.UniqueConstraint(fields=('property', 'owner'), name='uniq_ownership_per_property')],
            },
        ),
    ]
