# Generated by Django 5.2.2 on 2026-09-21 10:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_owner_importbatch_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='kind',
            field=models.CharField(choices=[('adhoc', 'Ad hoc expense'), ('utility', 'Utility bill')], default='adhoc', help_text='Ad hoc cost, or a utility bill (managed via a utility type).', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual entry'), ('airbnb_csv', 'Airbnb CSV import'), ('utility_bill', 'Utility bill'), ('other', 'Other import')], default='manual', max_length=30),
        ),
        migrations.CreateModel(
            name='UtilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Electricity', max_length=120)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-yearly'), ('yearly', 'Yearly'), ('other', 'Other')], default='quarterly', max_length=20)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('apportionment', models.CharField(choices=[('none', 'No apportionment (100% deductible)'), ('area', 'By floor area of the let'), ('custom', 'Custom percentage')], default='area', help_text='How the claimable portion is worked out (usually by floor area).', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utility_types', to='ledger.category')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_types', to='ledger.property')),
            ],
            options={
                'ordering': ['property__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UtilityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total bill amount (before apportionment).', max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paid', models.BooleanField(default=True)),
                ('attachment', models.FileField(blank=True, help_text='The bill PDF/image.', null=True, upload_to='bills/%Y/%m/')),
                ('extracted', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_bill', to='ledger.expense')),
                ('utility_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='ledger.utilitytype')),
            ],
            options={
                'ordering': ['-bill_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='utilitytype',
            constraint=models.UniqueConstraint(fields=('property', 'name'), name='uniq_utility_type_per_property'),
        ),
    ]
