# Generated by Django 5.2.2 on 2026-09-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_expense_kind_alter_expense_source_utilitytype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitytype',
            name='coverage_start',
            field=models.DateField(blank=True, help_text="Start tracking coverage from this date. Leave blank to use the property's purchase date.", null=True),
        ),
    ]
