# Generated by Django 5.2.2 on 2026-09-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_utilitytype_coverage_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='effective_life_is_estimate',
            field=models.BooleanField(default=False, help_text='Effective life was estimated (e.g. read from a receipt by AI) rather than taken from the ATO effective-life schedule — worth verifying.'),
        ),
    ]
