# Generated by Django 5.2.2 on 2026-09-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_asset_effective_life_is_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, help_text='A photo of the asset (optional).', null=True, upload_to='assets/%Y/%m/'),
        ),
    ]
