# Generated by Django 5.2.2 on 2026-09-21 14:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_asset_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_year', models.CharField(blank=True, max_length=12)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('nights_booked', models.PositiveIntegerField(blank=True, null=True)),
                ('avg_night_stay', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('service_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('source', models.CharField(default='airbnb_pdf', max_length=30)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_summaries', to='ledger.listing')),
            ],
            options={
                'verbose_name_plural': 'earnings summaries',
                'ordering': ['-period_end', '-period_start'],
                'constraints': [models.UniqueConstraint(fields=('listing', 'period_start', 'period_end'), name='uniq_earnings_summary_period')],
            },
        ),
    ]
