# Generated by Django 5.2.2 on 2026-09-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_earningssummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='default_apportionment',
            field=models.CharField(choices=[('none', 'No apportionment (100% deductible)'), ('area', 'By floor area of the let'), ('area_nights', 'By floor area × nights booked'), ('custom', 'Custom percentage')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='apportionment',
            field=models.CharField(choices=[('none', 'No apportionment (100% deductible)'), ('area', 'By floor area of the let'), ('area_nights', 'By floor area × nights booked'), ('custom', 'Custom percentage')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='utilitytype',
            name='apportionment',
            field=models.CharField(choices=[('none', 'No apportionment (100% deductible)'), ('area', 'By floor area of the let'), ('area_nights', 'By floor area × nights booked'), ('custom', 'Custom percentage')], default='area', help_text='How the claimable portion is worked out (by floor area, or floor area × nights booked).', max_length=20),
        ),
    ]
