# Generated by Django 5.2.2 on 2026-09-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_alter_category_default_apportionment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='report_file',
            field=models.FileField(blank=True, help_text='The earnings-report PDF exactly as imported, kept per batch so every figure can be traced back to the document that produced it.', upload_to='income_reports/%Y/%m/'),
        ),
    ]
