# Generated by Django 5.2.2 on 2026-09-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_importbatch_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.FileField(blank=True, help_text='Optional photo or mark for this property (PNG/JPG). When set, it is printed top-right on the financial-year report PDF.', upload_to='properties/%Y/%m/'),
        ),
    ]
