# Generated by Django 5.2.2 on 2026-10-04 04:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual entry'), ('airbnb_csv', 'Airbnb CSV import'), ('utility_bill', 'Utility bill'), ('receipt_capture', 'Receipt capture'), ('other', 'Other import')], default='manual', max_length=30),
        ),
        migrations.CreateModel(
            name='UnallocatedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='The photographed receipt.', upload_to='unallocated/%Y/%m/')),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Read with AI'), ('allocated', 'Allocated')], default='pending', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.localdate, help_text='Capture date.')),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('extracted', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, help_text='Suggested category (AI guess, or chosen by hand).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ledger.category')),
                ('expense', models.ForeignKey(blank=True, help_text='The ledger expense this receipt was allocated to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ledger.expense')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unallocated_expenses', to='ledger.property')),
            ],
            options={
                'verbose_name': 'unallocated expense',
                'verbose_name_plural': 'unallocated expenses',
                'ordering': ['-created_at'],
            },
        ),
    ]
