# Generated by Django 5.2.2 on 2026-10-05 04:24

import django.db.models.deletion
from django.db import migrations, models


def copy_asset_images(apps, schema_editor):
    """Move each asset's single image into the new AssetPhoto collection.

    The stored file itself is untouched — the AssetPhoto just points at the
    same path — so nothing is re-encoded or duplicated on disk.
    """
    Asset = apps.get_model("ledger", "Asset")
    AssetPhoto = apps.get_model("ledger", "AssetPhoto")
    for asset in Asset.objects.exclude(image="").exclude(image__isnull=True):
        AssetPhoto.objects.create(asset_id=asset.pk, image=asset.image.name)


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_alter_expense_source_unallocatedexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='assets/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='ledger.asset')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.RunPython(copy_asset_images, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='asset',
            name='image',
        ),
    ]
